### ISSUE TITLE
$app->getVersion() cannot be called in setup.php

### ISSUE THREAD

**Issue by bclindner** [rthackston-gsu/discussIT#39]
When deploying the site from scratch, PHP returns a fatal error when launching the site without an already initialized database (i.e. to setup.php). 

This is due to line 8 of the [head.php](https://github.com/rthackston-gsu/discussIT/blob/master/src/include/head.php) file in the includes - it tries to run `$app->getVersion()`, but that returns an error until the database is initialized through setup. 

When the PHP snippet is removed from this line, the setup.php page loads as usual.

**Comment by rthackston-gsu** [comment]
Resolved.
